# Generated by Django 3.0.6 on 2020-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetest',
            name='test_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
